### ISSUE TITLE
Ensure that GZIP compression is turned on for CloudFront assets

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-general#17]
This'll improve data-load times by clients.

**Comment by mileswwatkins** [comment]
And make sure that _we're_ not GZIPping the data ahead of time ourselves!

**Comment by mileswwatkins** [comment]
Recently removed GZIP from liveblog code, too; see if we can ensure GZIP there too.

**Comment by mileswwatkins** [comment]
Tested that a GZIP compression "Behavior" will work for both legacy/existing files (that are already GZIP'd before upload to S3, and have the metadata tag to indicate this encoding), and for new files (that are stored uncompressed on S3).

- https://console.aws.amazon.com/cloudfront/home#distribution-settings:E37FA9N6BBM95K
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

Want to check this by turning on compression for _all_ `apps.npr.org` assets; that's the only step left at this point. Conferring with @alykat about it.

**Comment by mileswwatkins** [comment]
We're testing this on `apps.npr.org/dailygraphics/*` starting tomorrow afternoon; Aly and I have a meeting set up to review any potential fallout.

**Comment by mileswwatkins** [comment]
Eads:

> nope! the gzipping for s3 is in a lot of ways a legacy feature
> I think it's preferable to just do that at the CDN layer

**Comment by mileswwatkins** [comment]
Tyler:

> the only thing we saw issues with in gzipping was video
> (so by proxy audio is probably bad, we just haven't done it)

We should check on some audio files and video files, if they're present in `s3://apps.npr.org`.

**Comment by alykat** [comment]
A couple audio examples off the top of my head:
http://apps.npr.org/lookatthis/posts/album-art/
https://apps.npr.org/music-memoriam-2013/
https://apps.npr.org/dailygraphics/graphics/march-for-our-lives-soundscapes-t-20180329/
([on this page](https://www.npr.org/2018/04/02/598287888/photos-why-they-marched-in-their-own-words))

With the examples I can think of that involve video, the video files don't live on apps.npr.org.

**Comment by mileswwatkins** [comment]
I looked through all 174k files on that bucket, and there are a couple video files in `dailygraphics`:

```
dailygraphics/graphics/cosplay2-20160721/assets/riki-lecotey.mp4
dailygraphics/graphics/sound-hovercraft-20160721/assets/riki-lecotey.mp4
```

And there are also video files within in a handful of projects:

```
audiogram-videos
austin
austin15
bats
best-songs-2015-so-far
best-songs-2015
borderland
lookatthis
naughty-or-nice
radex
rockymountain-vr
```

So we have a good set to test with.

**Comment by mileswwatkins** [comment]
Actually, it doesn't look like `audio/mpeg` or `video/mp4` are even compressed by CloudFront! We weren't compressing them vefore, and I guess we don't need to sweat 'em now.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-cloudfront-file-types

**Comment by mileswwatkins** [comment]
No problems with `dailygraphics/*`, from what we can see. We're letting everything sit for one day (just in case someone reports an issue), and then tomorrow will turn on auto-compression for everything in the entire bucket (ie, `*`).

**Comment by mileswwatkins** [comment]
Auto-GZIP turned on for all of `apps.npr.org`.
