### ISSUE TITLE
Some variables missing for one county in SD

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-general#31]
Oglala Lakota county, recently renamed and with new FIPS code, is missing Census information in `extra-data/sd-extra.json`:

```
  "46102": {
    "unemployment": 11.8,
    "past_margin": "D +78",
    "census": null
  },
```

This should probably be manually patched, and make sure this patch makes it to the front-end repo.

**Comment by goldfarb** [comment]
Manually entered census data from 2016 / 5 year ACS for SD 46102
Updated the census data / made a note in data.py

- https://github.com/nprapps/elections18-graphics/commit/1fd1646e5297084a89f1d633e0b1884d4c835670#diff-81ac9d43d8e988f39a56e48fa219e26f

-https://github.com/nprapps/elections18-general/commit/75e5ee390d84643a2b743b49ab3132953219b03a#diff-c0ad4e935b8fad4a9f108777dbd84a17

![sd](https://user-images.githubusercontent.com/3722037/47239612-d6229f00-d3b3-11e8-805f-85512c1ca585.png)
